name: build

on: 
  push:
    paths:
    - '**.cpp'
    - '**.hpp'
    - '**.c'
    - '**.h'
    - '**.rc'
    - '**.def'
    - '**.lib'
    - '**.dll'
    - '**.build'
    - '**.bmp'
    - '**.png'
    - '**.jpg'
    - '**.webp'
    - '.github/**'
    - 'res/**'
    - 'src/**'
    - 'subprojects/**'
    - '.gitmodules'
  release:
    types: published

jobs:
  Build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 'pypy3.9'
        cache: 'pip'

    - name: Install meson and ninja
      run: pip install -r .github/workflows/requirements.txt

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86

    - name: Configure
      run: meson setup bin --buildtype=release

    - name: Compile
      run: meson compile -C bin --verbose --load-average=100

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: github.event_name != 'release'
      with:
        name: FusionPath
        path: ./bin/fusionpath.exe

    - name: Upload release
      uses: AButler/upload-release-assets@v2.0
      if: github.event_name == 'release'
      with:
        files: './bin/fusionpath.exe'
        repo-token: ${{ secrets.GITHUB_TOKEN }}